import {
  IAvailability,
  ICondition,
  IMetaDescriptionType,
  IOpenGraphTagsType,
  ISalePriceType,
  ISearchIn,
  IStock,
} from '../../../../models/product';
import { IMemberships } from '../../../../models/user';

export const PRODUCT_STOCKS: Array<IStock> = [
  {
    name: 'In Stock',
    id: 'in',
  },
  {
    name: 'SOLD',
    id: 'out',
  },
  {
    name: 'Low stock',
    id: 'low',
  },
];

export const PRODUCT_AVAILABILITY: Array<IAvailability> = [
  {
    id: 'all',
    name: 'Any availability status',
  },
  {
    id: '1',
    name: 'Only enabled',
  },
  {
    id: '0',
    name: 'Only disabled',
  },
];

export const PRODUCT_SEARCH_IN: Array<ISearchIn> = [
  {
    id: 'name',
    name: 'Name',
  },
  {
    id: 'sku',
    name: 'SKU',
  },
  {
    id: 'description',
    name: 'Description',
  },
];

export const PRODUCT_CONDITION: Array<ICondition> = [
  {
    id: 262,
    name: '',
  },
  {
    id: 292,
    name: 'Used',
  },
];

export const PRODUCT_MEMBERSHIPS: Array<IMemberships> = [
  {
    id: '4',
    name: 'General',
  },
];

export const PRODUCT_SALE_PRICE_TYPE_DOLLAR_ID = '$';
export const PRODUCT_SALE_PRICE_TYPE_PERCENTAGE_ID = '%';

export const PRODUCT_SALE_PRICE_TYPE: Array<ISalePriceType> = [
  {
    id: PRODUCT_SALE_PRICE_TYPE_DOLLAR_ID,
    name: '$',
  },
  {
    id: PRODUCT_SALE_PRICE_TYPE_PERCENTAGE_ID,
    name: '%',
  },
];

export const PRODUCT_SHIPPING_TO_ZONE_CONTINENTAL_US_ID = 1;

export const PRODUCT_OPEN_GRAPH_TAGS_TYPE_AUTOGENERATED_ID = '0';
export const PRODUCT_OPEN_GRAPH_TAGS_TYPE_CUSTOM_ID = '1';

export const PRODUCT_OPEN_GRAPH_TAGS_TYPE: Array<IOpenGraphTagsType> = [
  {
    id: PRODUCT_OPEN_GRAPH_TAGS_TYPE_AUTOGENERATED_ID,
    name: 'Autogenerated',
  },
  {
    id: PRODUCT_OPEN_GRAPH_TAGS_TYPE_CUSTOM_ID,
    name: 'Custom',
  },
];

export const PRODUCT_META_DESCRIPTION_TYPE_AUTOGENERATED_ID = 'A';
export const PRODUCT_META_DESCRIPTION_TYPE_CUSTOM_ID = 'C';

export const PRODUCT_META_DESCRIPTION_TYPE: Array<IMetaDescriptionType> = [
  {
    id: PRODUCT_META_DESCRIPTION_TYPE_AUTOGENERATED_ID,
    name: 'Autogenerated',
  },
  {
    id: PRODUCT_META_DESCRIPTION_TYPE_CUSTOM_ID,
    name: 'Custom',
  },
];
